services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'HopperE2e-Only!2026'
    ports:
      - '127.0.0.1:14365:1433'
    volumes:
      - ../db/backup:/backup:ro
      - ../db/migrate.sql:/migrate.sql:ro
